permalink: /blog/:categories/:year/:month/:day/:title
markdown: redcarpet

paginate_path: "blog/page:num"
paginate: 3
highlighter: rogue
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
deploy: false
encoding: utf-8

gems: ['jekyll-paginate']

exclude: ['*.Rmd']

packages:
- rbefdata
- bhl
- citeulike
- dryad
- flybase
- neotoma
- npn
- rAltmetric
- ecoengine
- rdatacite
- rEBI
- reml
- renterz
- rfigshare
- rfishbase
- rfisheries
- rgbif
- rhindawi
- rImpactStory
- ritis
- RMendeley
- ropensnp
- rpensoft
- rplos
- rspringer
- rvertnet
- taxize
- treebase
- ecoengine
